### ISSUE TITLE
Dead project

### ISSUE THREAD

**Issue by ciokan** [auth0/lock-passwordless#128]
Dependencies are way behind and it hasn't been updated in a long time. I've seen questions not being answered for months. Any integration I tried with an ionic app has failed due to this package pulling dependencies from a version `6.x.x` from `auth0-js` while that package is at version `8.x.x`

**Comment by hzalaz** [comment]
The project is not dead, but we have been focused on the classic lock.js and auth0.js lately but we'll come back to it and update its dependencies once we are done with other work.

If you are willing to take a stab at it please send us a Pull Request and we'll try to review it quickly.

On another topic, auth0.js in theory shouldn't make your integration fail, even if is an old version, so please open another issue with the error you are getting and if necessary steps to reproduce.

Thanks
