### ISSUE TITLE
New API returns short access_token and no id_token by default and breaks Lock

### ISSUE THREAD

**Issue by dinvlad** [auth0/lock-passwordless#132]
Hi all,

My passwordless Lock suddenly stopped working (without any changes on my part) because the new authentication API apparently returns a short _access_token_ and no _id_token_ by default. As a result of that and #130, this change breaks Lock if we rely on the old behavior (incl. using `parseHash()` and `getProfile()` that both expect an _id_token_).

Could this Lock be updated according to the new API?

EDIT: this behavior is happening to a **stock** configuration of Lock. If we specify _audience_, the return _access_token_ is "fat" but there's no _id_token_ in either case (and that one is required by `parseHash()` and `getProfile()`).

Thanks

**Comment by dinvlad** [comment]
False alarm, it turns out I checked strict OIDC conformity in my client settings, which lead to this behavior (namely returning only a short `access_token` when I don't specify an audience)

**Comment by hyena** [comment]
Is it just me or does the documentation on https://auth0.com/docs/client-auth/current/server-side-web#exchange-the-code-for-an-id_token request strict OIDC conformity and yet the example exchange code for e.g. cUrl doesn't specify an audience and hence doesn't retrieve an id_token?
