### ISSUE TITLE
state and refresh_token return undefined when logging in with emailcode

### ISSUE THREAD

**Issue by braydie** [auth0/lock-passwordless#133]
I'm using version 2.2.3 of passwordless lock. I have the following code within a function:

```
var lock = new Auth0LockPasswordless("x", "auth0domain");
lock.emailcode({autoclose: true}, function (error, profile, id_token, access_token, state, refresh_token) {
    if (!error) {
        localStorage.setItem(token, id_token);
        console.log(refresh_token);
    }
});
```

When this code is invoked, `state` and `refresh_token` return undefined.

Am I doing something wrong?

**Comment by braydie** [comment]
All sorted now

http://stackoverflow.com/questions/42975847/can-i-get-a-refresh-token-using-auth0-passwordless-lock-in-javascript?noredirect=1#comment73052934_42975847

**Comment by luisrudge** [comment]
Thanks for sharing the answer with us! 🎉
