### ISSUE TITLE
Outdated dependencies causing old version of react to load

### ISSUE THREAD

**Issue by jeffjenk** [auth0/lock-passwordless#139]
I recently updated to the latest version of React, but my React Developer Tools plugin was complaining about React still being outdated.

![screen shot 2017-07-30 at 8 25 28 am](https://user-images.githubusercontent.com/936604/28751173-08b8e0a4-7501-11e7-93af-624739087dec.png)

After a little bit of googling I found the following issue logged on React-devtools: https://github.com/facebook/react-devtools/issues/813 which was the same problem I was having. I followed the instructions provided to check where the old version of react was coming from and it turned out to be lock-passwordless. 

I have switched to authenticating directly with auth0-js so I just took lock-passwordless out of my application, but I thought I would bring it to your attention.

**Comment by luisrudge** [comment]
Thanks. This project uses an old version of React indeed. We're adding passwordless support to Lock itself (instead of keeping it as a separate project), but I'll try to do an update in this library to update the dependencies.
