### ISSUE TITLE
Module name to use in angular?

### ISSUE THREAD

**Issue by nowherenearithaca** [auth0/lock-passwordless#142]
I'm trying to load the module in angular, but can't quite seem to guess the module name to use.

Not sure if you know, but I'm sure I'm missing something simple.  The js s definitely being included in the packaged vendor.js that I build.

Here's the basic syntax i'm using (without guess the name right yet!)

angular .module('myApp', [module1name, module2name,...])

I've tried  auth0.lockPasswordless, auth0.lock-passwordless, and auth0.lock-Passwordless

**Comment by luisrudge** [comment]
Not sure how angular handles globals, but we expose a global variable called `Auth0LockPasswordless ` when you use the cdn.

https://github.com/auth0/lock-passwordless/blob/master/src/browser.js#L15

**Comment by nowherenearithaca** [comment]
Yes - I realized that I didn't need to add it as a module.  Thanks!
