### ISSUE TITLE
Prefill E-Mail Address

### ISSUE THREAD

**Issue by kohlera** [auth0/lock-passwordless#149]
is it possible to prefill the email adress when using
`this.lock.emailcode(options, this._doAuthentication.bind(this));`

By adding `options.prefill = {email: 'someone@example.com'}` it does not work.

**Comment by luisrudge** [comment]
This is supported in the new version: https://github.com/auth0/lock

**Comment by fredicious** [comment]
The prefill option with `Auth0LockPasswordless` is not working in the V11.

**Comment by Pluto1010** [comment]
Any updates on this? Would also like to prefill the field for email or the phone number while using Passwordless mode.

**Comment by luisrudge** [comment]
This was just added in the latest version of Auth0LockPasswordlesss: https://github.com/auth0/lock/blob/master/CHANGELOG.md#v11110-2018-10-23
