### ISSUE TITLE
Functionality issues

### ISSUE THREAD

**Issue by sanntu** [auth0/lock-passwordless#33]
**Safari:**
- [ ] **Enter** no selecciona el país.
- [ ] Cuando el usuario hace click para seleccionar el país, no funciona/no lo detecta. (No puedo volver del listado de países sin que cierre el modal)
- [ ] **Escape** no vuelve "atrás" la lista de países.

**Comment by gnandretta** [comment]
@sanntu d6627ba9fb585c4fc21158e97d0011e88d2e932c fixed all the items on my machine but I'll let you double-check.

I also believe that was responsible for the similar issues happening on an iPad mini.

**Comment by sanntu** [comment]
Genial. Fixed.
