### ISSUE TITLE
Settle on Lock instances lifecycle 

### ISSUE THREAD

**Issue by gnandretta** [auth0/lock-passwordless#56]
In the current implementation, once a Lock is closed it can't be opened again which can be confusing for our users.

**Comment by PanosJee** [comment]
I had this question too, I don't understand if this is a bug or a feature

**Comment by gnandretta** [comment]
In the next release it will possible to reopen the lock after it has been closed.

**Comment by PanosJee** [comment]
Thanks @gnandretta, are you referring to major or minor release?

**Comment by gnandretta** [comment]
@PanosJee It'll be a mayor release
