### ISSUE TITLE
Exception in console if invalid code is entered

### ISSUE THREAD

**Issue by Lourenc** [auth0/lock-passwordless#78]
Hello!

Issue is happening if user enters invalid code to Passwordless Lock dialog. There's an error in console saying the following: `POST https://sample.auth0.com/oauth/ro 401 (Unauthorized)`. Error object is successfully received to `callback`, but I suppose it shouldn't be logged to console.

Could you, please, fix that?

**Comment by cristiandouce** [comment]
@Lourenc if it's an XHR 401 response Error, then all XHR get by default logged into the browser console (in dev tools)

You can opt out by:

![image](https://cloud.githubusercontent.com/assets/367429/10946892/89a4d71e-8303-11e5-9652-0a974cb26b87.png)

> Chrome

Do you mind sharing a screenshot though? I don't see any active `console.log()` call from the codebase.

Thanks!

**Comment by Lourenc** [comment]
@cristiandouce thanks, you're right, it's an XHR 401 Error.

**Comment by cristiandouce** [comment]
:dancers: Thank you!
