### ISSUE TITLE
Distribute a standard build for npm

### ISSUE THREAD

**Issue by impronunciable** [auth0/lock-passwordless#82]
I want to use lock-passwordless along with webpack. Instead of adding loaders I think the right approach will be to distribute with npm a version similar to the standalone.

**Comment by gnandretta** [comment]
Hi @impronunciable, you're right. Using lock-passwordless with any module bundler should be easier. I'll work on this and would love to have some feedback before releasing it.

**Comment by impronunciable** [comment]
Thanks!

**Comment by beneliflo** [comment]
@impronunciable please try v2.2.0 and let us know if you have any issues

**Comment by woloski** [comment]
:iphone:

**Comment by impronunciable** [comment]
Thank you for the follow up. I'll get back from vacations next week and
will try it.
