### ISSUE TITLE
NPM package error

### ISSUE THREAD

**Issue by montogeek** [auth0/lock-passwordless#94]
Hi!

Thanks for publish this package to npm, on our project we were using the CDN script, it worked perfectly, after switching to the npm package, the following errors are happening:
![screen shot 2016-01-27 at 15 01 20](https://cloud.githubusercontent.com/assets/1002461/12627851/365ce392-c50e-11e5-9f5b-c01fc36a4241.png)

The first error happens when fetching the gravatar image, the second one when you submit your email.

We are using:
React 0.14.6
Webpack 1.12.9

I think is probably related to this issue: https://github.com/facebook/react/issues/2402 since this package install its own React version (0.14.5)

**Comment by montogeek** [comment]
After update our React dependencies to be the same as this package (0.14.5) the last error was fixed, so.

**Comment by gnandretta** [comment]
@montogeek Thanks for reporting the issue!

I've fixed the `Uncaught TypeError: (0 , _blueimopMd.md5) is not a function` error and upgraded the react dependency to `0.14.6`.

I'll need some more time to test before making a proper release tomorrow. In the meantime, I've pushed the changes to the branch `webpack-fix`. So, you can continue with the development of your application with the following dependency if you want to:

```
"auth0-lock-passwordless": "auth0/lock-passwordless#"
```

**Comment by montogeek** [comment]
Thank you so much!

**Comment by montogeek** [comment]
Is there any problem is you leverage the React version installed to NPM?
Instead of specify a version, leave npm decide the last version, like `^0.14`.

**Comment by gnandretta** [comment]
I had some issues before during development were I ended up with different versions for some react packages. Anyways, I've relaxed the dependency version, lets see how it plays out.

**Comment by montogeek** [comment]
Any idea why I am getting an empty folder?
package.json
`"auth0-lock-passwordless": "auth0/lock-passwordless.git#webpack-fix"`

![screen shot 2016-01-28 at 19 20 57](https://cloud.githubusercontent.com/assets/1002461/12663252/6697c3d8-c5f4-11e5-9e9c-dae20302d471.png)
![screen shot 2016-01-28 at 19 22 05](https://cloud.githubusercontent.com/assets/1002461/12663256/739bf338-c5f4-11e5-94a9-f7762afa5684.png)

**Comment by gnandretta** [comment]
@montogeek I've released `2.2.2`.

**Comment by montogeek** [comment]
Working smoothly, thank you!
