### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by montogeek** [auth0/lock-passwordless#96]
Hi!

Is there any plan to support React Native?

Thanks!

**Comment by gnandretta** [comment]
Hi, we have [react-native-lock-ios](https://github.com/auth0/react-native-lock-ios) that is a wrapper for the iOS Lock library and [react-native-lock-android](https://github.com/auth0/react-native-lock-android) for Android. Both support passwordless authentication. They look different than lock-passwordless, but and update is on the way.

**Comment by montogeek** [comment]
Thank you. This should be added to the Readme, so other people can find them easily :)

**Comment by gnandretta** [comment]
Done, thanks for the suggestion! :dancers:
